ArI = 'ArI'
Inc = 'Inc.'
print(2024, ArI, Inc, sep = ' ')
var1 = input("What is your name:")
hello = 'Hello'
print(hello, var1, sep =' ')
var2 = input("What is your favorite food:")
I = 'I'
heard = 'heard'
you = 'you'
like = 'like'
print(I, heard, you, like, var2, sep =' ')